ARG base=balenalib/%%BALENA_MACHINE_NAME%%-alpine

FROM ${base}

RUN wget -O - https://bintray.com/ookla/download/download_file?file_path=ookla-speedtest-1.0.0-$(uname -m)-linux.tgz | tar xzvf -
RUN mv speedtest /
COPY crontab /etc/crontabs/root
ENTRYPOINT ["crond", "-f"]
